### PR TITLE
Expose the parser so it can be used with existing logs without watching

### PR DESCRIPTION
**Pull request by KennethSundqvist**
This is useful if you want to parse existing logs to analyse them or develop the parser itself (I'm interested in both).

See the changes to the README for the full details, and then the code of course.

### CODE REVIEW

**Comment by AlexAllocated** [comment]
Love it. Thanks!

This is one of the problems I was going to solve myself. I'm building a tracker and want to be able to start it mid-game. This is exactly what I need to do that :D

**Comment by AlexAllocated** [comment]
I'll publish to npm once I've used it a bit. I'm about to incorporate it into [my deck tracker app](https://github.com/codetunnel/hearthtunnel-deck-tracker). I finally finished the deck builder portion of the app and will now be implementing the actual tracker. With this parse function I should be able to parse the whole log file, keeping track of game overs until it hits the end of the log file. Then I can let the tracker begin and track normally from there :D

**Comment by KennethSundqvist** [comment]
Nice! I'll take a look at the deck tracker/builder.

I've also been working on **turn** and **mulligan** events and have it pretty much finished. Will try to make a PR of that this week.

**Comment by AlexAllocated** [comment]
Wonderful!

**Comment by AlexAllocated** [comment]
This change is now published to npm btw.

**Pull request merged**
